; ------------------------------------------------
; variables for accent colors
; ------------------------------------------------

[Variables]

; index of accent color used
colorCurrentI=7

; RGB values for current color
colorCurrentR=50
colorCurrentG=180
colorCurrentB=230

; custom accent color from the picker
colorExample0=

; predefined accent colors
colorExample1 = 238,27,36
colorExample2 = 255,135,0
colorExample3 = 255,215,5
colorExample4 = 0,200,80
colorExample5 = 0,145,145
colorExample6 = 50,180,230
colorExample7 = 100,145,255
colorExample8 = 170,120,250
colorExample9 = 225,0,115
colorExample10 = 75,80,85

; selected accent color
colorAccent = #colorExample[#colorCurrentI]#
