; ------------------------------------------------
; light color scheme for the suite
; ------------------------------------------------

[Variables]

colorWindowBackground = 255,255,255
colorWindowBorder = 150,150,150

colorWindowIcons = 0,0,0

colorWindowFont1 = 0,0,0
colorWindowFont2 = 100,100,100


colorWindowPageBorder = 220,220,220


colorPageEffect1 = 30,30,30,10
colorPageEffect2 = 250,250,250,10

colorNavEffect1 = 30,30,30,10
colorNavEffect2 = 250,250,250,10