; ---------------------------------------------
; dark color scheme for the suite
; ---------------------------------------------

[Variables]

colorWindowBackground = 20,20,20
colorWindowBorder = 150,150,150

colorWindowIcons = 255,255,255

colorWindowFont1 = 255,255,255
colorWindowFont2 = 100,100,100


colorWindowPageBorder = 100,100,100


colorPageEffect1 = 30,30,30,10
colorPageEffect2 = 250,250,250,10