; ---------------------------------------------
; Nord color scheme for the suite
; ---------------------------------------------

[Variables]

colorBackground1 = 45,50,65
colorBackground2 = 50,55,70
colorBackground3 = 45,50,65

colorTile1 = 60,65,80
colorTile2 = 70,100,140
colorTile3 = 250,250,250

colorObject1 = 250,250,250
colorObject2 = 65,75,95
colorObject3 = 65,75,95

colorFont1 = 250,250,250
colorFont2 = 200,200,200
colorFont3 = 255,0,0