; ---------------------------------------------
; custom color scheme for the suite
; ---------------------------------------------

[Variables]

colorWindowBackground = 120,12,90
colorWindowBorder = 240,210,210

colorWindowIcons = 240,210,210

colorWindowFont1 = 240,210,210
colorWindowFont2 = 230,115,160


colorWindowPageBorder = 204,14,115


colorPageEffect1 = 30,30,30,10
colorPageEffect2 = 250,250,250,10