; ---------------------------------------------
; variables used in the Settings skin
; ---------------------------------------------

[Variables]

; ---------------------------------------------
; main window
; ---------------------------------------------

; window dimensions
WindowWidthTotal = (1000 * #valueUserScale#)
WindowHeightTotal = (700 * #valueUserScale#)
WindowBorderThickness = (1 * #valueUserScale#)

; panel dimensions
LeftPanelWidth = (300 * #valueUserScale#)
RightPanelWidth = (700 * #valueUserScale#)

LeftPanelFull = (300 * #valueUserScale#)
LeftPanelColl = (50 * #valueUserScale#)

RightPanelFull = (700 * #valueUserScale#)
RightPanelColl = (950 * #valueUserScale#)

; panel margins
LeftPanelMarginBig = (30 * #valueUserScale#)
LeftPanelMarginSmall = (5 * #valueUserScale#)

RightPanelMarginBig = (30 * #valueUserScale#)
RightPanelMarginSmall = (5 * #valueUserScale#)

; title bar height
TitleBarHeight = (50 * #valueUserScale#)



; ---------------------------------------------
; navigation glyphs
; ---------------------------------------------


NavButtonSize = (40 * #valueUserScale#)
NavButtonBorderThickness = 0.5





; ---------------------------------------------
; text elements
; ---------------------------------------------

; window title offsets
WindowTitleOffsetL = (25 * #valueUserScale#)
WindowTitleOffsetU = (15 * #valueUserScale#)

; profile data offsets
ProfileDataOffsetL = (10 * #valueUserScale#)
ProfileDataOffsetUD = (10 * #valueUserScale#)



; ---------------------------------------------
; header elements
; ---------------------------------------------

HeaderStack = (80 * #valueUserScale#)

ProfilePictureR = (30 * #valueUserScale#)

PageTitleGlyphOffsetLR = (20 * #valueUserScale#)




; ---------------------------------------------
; left panel elements
; ---------------------------------------------

; section labels
SectionStack1 = (145 * #valueUserScale#)
SectionStack2 = (275 * #valueUserScale#)
SectionStack3 = (505 * #valueUserScale#)

; page button
PageButtonOffsetB = (5 * #valueUserScale#)
PageButtonWidth = (#LeftPanelWidth# - (2*#LeftPanelMarginSmall#))
PageButtonHeight = (40 * #valueUserScale#)
PageButtonBorderThickness = 0.5

; page indicator
PageIndicatorWidth = (3 * #valueUserScale#)
PageIndicatorHeight = (20 * #valueUserScale#)
PageIndicatorRadius = (2 * #valueUserScale#)

; page icon
PageIconSize = (24 * #valueUserScale#)
PageIconOffsetL = (8 * #valueUserScale#)

; page label
PageLabelOffsetL = (10 * #valueUserScale#)



